// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://cnctvqeyuwzsfcpargqo.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImNuY3R2cWV5dXd6c2ZjcGFyZ3FvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDU1NzA4MDAsImV4cCI6MjA2MTE0NjgwMH0.ZbDIgW5zoteqR0uA7PvGBn0ztAkE8NWzbo1gme8Mp48";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);